### ISSUE TITLE
Any plans for further development?

### ISSUE THREAD

**Issue by indigoxela** [firetray-updates/FireTray#2]
Hi,
I just built and installed your FireTray fork on Linux in Thunderbird 60.2.
It has some issues, but first of all:

Are there any plans for further development or maintenance, or is this fork just meant to be a quick solution for yourself until someone else comes up with a new extension?

As far as I can see, there's no usable alternative for Linux regarding a tray icon showing the number of unread mails, which is compatible with Thunderbird 60+.
And it doesn't look like there will be one in near future.
So your work is highly appreciated.

**Comment by firetray-updates** [comment]
Hi,

this is just a fork to get FireTray working.  FireTray is good enough for me, I don't really care about having a counter or other fancy features, I just want to be able to hide Thunderbird and have some indication when I have something changes in my inbox (i.e., "message count type" set to "new messages").

I've seen standalone applications that manually parse Thunderbird's database to show a tray icon with a counter. This is definitely an interesting approach and it's probably more future proof than relying on an extension, if you consider that Mozilla is limiting more and more what extensions can do.

That said, I think I'll keep using FireTray for as long as I can get it to work and I don't plan on doing a lot more than what I already did.

**Comment by indigoxela** [comment]
Hi,
I'm watching Birdtray also. Yes, the approach is interesting but unfortunately prone to errors (wrong message count...).
So I'll do the same as you do - trying to keep Firetray running as long as possible, hoping someone else comes up with a better idea.
