### ISSUE TITLE
Custom Icons

### ISSUE THREAD

**Issue by jamesrobb** [firetray-updates/FireTray#7]
Hello,

I notice that setting custom icons does not appear to work when using this plugin with appindicator. Is this just me?

If it is not possible to set custom icons through the GUI, what line of code could I change to set a custom SVG to be the default icon for thunderbird? I'd like to set the icon to a grey scale version of the thunderbird logo to match the rest of my tray icons.

I copied a grey scale SVG to /usr/share/icons/Papirus/32x32/apps/thunderbird-nomessages.svg, and have replaced every instance of "firetray.StatusIcon.defaultAppIconName" I can find in the code with "thunderbird-nomessages", but unfortunately this hasn't worked.

Thanks,

**Comment by firetray-updates** [comment]
Fixed: https://github.com/firetray-updates/FireTray/commit/8e45faee70d3ff2cbe8404ea5660eff16c2a88f3

**Comment by jamesrobb** [comment]
Works!
